# Generated by Django 2.2 on 2019-06-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20190611_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='right',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='weight',
            field=models.CharField(choices=[(5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25)], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
