# Generated by Django 2.2 on 2019-06-11 22:48

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20190612_0009'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='question',
            managers=[
                ('randoms', django.db.models.manager.Manager()),
            ],
        ),
    ]
