# Generated by Django 2.2 on 2019-06-13 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_gamerecords'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameRecords',
            new_name='GameRecord',
        ),
    ]
